### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by iranathan** [tucnakomet1/Python-Who-Is-On-My-WiFi#1]
```PY
cat: /sys/devices/virtual/dmi/id/sys_vendor: No such file or directory
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    print(who_is_on_my_wifi.who())
  File "/usr/local/lib/python3.7/dist-packages/who_is_on_my_wifi.py", line 101, in who
    dev = device()
  File "/usr/local/lib/python3.7/dist-packages/who_is_on_my_wifi.py", line 155, in device
    nam = nam.decode("utf-8").split()[0]
IndexError: list index out of range
```
im am getting this error when i run.
code:
```PY
import who_is_on_my_wifi
print(who_is_on_my_wifi.who())
```

**Comment by tucnakomet1** [comment]
At first, thanks for reporting this issue.

Your issue means you don't have file `sys_vendor` in your PC. 
Just for sure type into your terminal `cat /sys/devices/virtual/dmi/id/sys_vendor`... But it's just for sure that you really don't have this file in this directory.

1) What type of Linux distribution do you use? 

2) Please type into your terminal `sudo find / -iname "sys_vendor"` to find `sys_vendor` in your PC.
- If the result is shown, please send it to me here and I will incorporate it into the script.
- If no result is shown, it means that you don't have the `sys_vendor` file anywhere on your PC (which would be strange). In this case please try the third step.

3) Type into terminal `sudo dmidecode -s system-manufacturer`. This  would have the same result as `sys vendor` command.
- If this works, please let me know and I'll update my script/ package.

Thanks in advance.

**Comment by tucnakomet1** [comment]
I found a few more bugs in the older version, so I just created version 1.1.3. 
Tested on 3 Linux devices, so it should already work. I would appreciate your response.
