### ISSUE TITLE
Unable to get the list of devices with this module

### ISSUE THREAD

**Issue by sunilk-n** [tucnakomet1/Python-Who-Is-On-My-WiFi#10]
I'm getting a RuntimeError when I run `wiom -w`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python37\lib\site-packages\who.py", line 43, in who
    answ = srp(devided, timeout=0.5, verbose=False)[0] # '0.5' because of double attempts per second
  File "c:\Python37\lib\site-packages\scapy\sendrecv.py", line 553, in srp
    filter=filter, nofilter=nofilter, type=type)
  File "c:\Python37\lib\site-packages\scapy\arch\windows\__init__.py", line 1061, in __init__
    "Sniffing and sending packets is not available at layer 2: "
RuntimeError: Sniffing and sending packets is not available at layer 2: winpcap is not installed. You may use conf.L3socket orconf.L3socket6 to access layer 3
```

I'm using python 3.7 and I'm also not able to install winpcap as no matching version is there for python 3.7

**Comment by tucnakomet1** [comment]
Hello, 

thank you for your report.

WIOM needs WinPcap or Npcap, so if [WinPcap](https://www.winpcap.org/install/) doesn't work, try installing Npcap from their [official](https://nmap.org/npcap/) website.

After installation everything should work. If not, let me know.
Have a nice day.

**Comment by sunilk-n** [comment]
I think there is no module named Npcap... `pip install Npcap` is not working. Even the WinPcap too.
And I have a doubt, if these modules were required by your module, then I think you should add these modules to the requirements of your package.

**Comment by tucnakomet1** [comment]
It's not a Python module so I can't add it to requirements, it's an API for capturing network traffic (more info [here](https://en.wikipedia.org/wiki/Pcap)). Here you have the download links for [WinPcap](https://www.winpcap.org/install/) and [Npcap](https://nmap.org/npcap/) so choose one of them, install it and everything should be alright.

I hope you understand and I hope it will work.
