### ISSUE TITLE
Does it work on mobile hotspots?

### ISSUE THREAD

**Issue by Amirabbas-MHR** [tucnakomet1/Python-Who-Is-On-My-WiFi#8]
Hey. Thanks for your great project. I used it for my mobile hot spot using who() function on my laptop(Ubuntu 20.04 LTS, python 3.8) . But even if multiple devices are connected to my phone, it only returns my laptop IP and other info.
What should I do?
![Screenshot from 2020-12-29 15-42-30(1)](https://user-images.githubusercontent.com/76734139/103283168-c7799e80-49a5-11eb-94b4-68f4a557e38e.png)

**Comment by tucnakomet1** [comment]
Hello. Thank you very much.

The answer is simple *(I hope)*, just run python as **sudo** and then it should work.

```bash
$ sudo python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import who_is_on_my_wifi as w
>>> w.who()
```
I hope it helped, if not, let me please know.
Have a nice day.

**Comment by Amirabbas-MHR** [comment]
It worked! I really appreciate your greate and fast support on this project and wish you luck ❤❤❤
